# Generated by Django 5.0.6 on 2024-06-27 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_code', models.CharField(choices=[('en', 'American English'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('fa', 'Persian'), ('fr', 'French'), ('es', 'Spanish'), ('ru', 'Russian'), ('de', 'German'), ('ja', 'Japanese'), ('it', 'Italian'), ('pt', 'Portuguese'), ('hi', 'Hindi')], max_length=2)),
                ('locale', models.CharField(max_length=100)),
                ('locale_code', models.CharField(choices=[('US', 'United States'), ('CN', 'simplified, PRC'), ('RU', 'Russia'), ('FR', 'France'), ('ES', 'Spain'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('BR', 'Brazil'), ('CA', 'Canada'), ('MX', 'Mexico'), ('IT', 'Italy'), ('JP', 'Japan'), ('IN', 'India')], max_length=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(choices=[('en', 'American English'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('fa', 'Persian'), ('fr', 'French'), ('es', 'Spanish'), ('ru', 'Russian'), ('de', 'German'), ('ja', 'Japanese'), ('it', 'Italian'), ('pt', 'Portuguese'), ('hi', 'Hindi')], max_length=2)),
                ('locale', models.CharField(max_length=100)),
                ('locale_code', models.CharField(choices=[('US', 'United States'), ('CN', 'simplified, PRC'), ('RU', 'Russia'), ('FR', 'France'), ('ES', 'Spain'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('BR', 'Brazil'), ('CA', 'Canada'), ('MX', 'Mexico'), ('IT', 'Italy'), ('JP', 'Japan'), ('IN', 'India')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('_username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('_password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.language')),
            ],
        ),
        migrations.AddConstraint(
            model_name='originlanguage',
            constraint=models.UniqueConstraint(fields=('language_code', 'locale_code'), name='unique_local_language_code'),
        ),
        migrations.AddField(
            model_name='translation',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dictionary.dictionary'),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.user'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.user'),
        ),
    ]
