# Generated by Django 5.0.6 on 2024-06-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='locale',
        ),
    ]
