# Generated by Django 5.0.6 on 2024-06-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_remove_language_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='language',
            name='locale_code',
        ),
        migrations.RemoveField(
            model_name='originlanguage',
            name='locale',
        ),
        migrations.AddField(
            model_name='language',
            name='origin_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dictionary.originlanguage'),
        ),
    ]
